### ISSUE TITLE
Column order output is not consistent when using joins

### ISSUE THREAD

**Issue by abalakumar083** [cmu-db/noisepage#1040]
So there's an issue with joins right now where the left table's columns and the right table's columns will be flipped in the output occasionally. For example the following queries,
```
CREATE TABLE xxx (id INT PRIMARY KEY, val INT);  
CREATE TABLE yyy (id INT PRIMARY KEY, val INT);
INSERT INTO xxx VALUES (1,1),(2,2),(3,3),(4,4);
INSERT INTO yyy VALUES (1,10),(2,9),(4,8);
select * from xxx INNER JOIN yyy ON xxx.id = yyy.id;
```
result in the following output:
```
 id | val | id | val 
----+-----+----+-----
  1 |  10 |  1 |   1
  2 |   9 |  2 |   2
  4 |   8 |  4 |   4
(3 rows)
```
The reason for this (well at least in the above example) is because the output tables are ordered in whatever order `regular_alias_table_map_` is iterated through (relevant function is `BinderContext::GenerateAllColumnExpressions` ), but since `regular_alias_table_map_` is a unordered map there's no set order for the iteration.

**Comment by apavlo** [comment]
@soumilm after we merge in the upcoming CTE PR.
