### ISSUE TITLE
Track Compilation Time in Jenkins

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#1053]
We need to start monitoring the compilation time of the system. This would be for comparison purposes for now (i.e., the build won't fail if things get slower). Once we start collecting this data, we can then decide how to enforce barriers or provide notifications.

We will add this to the 'Microbenchmark' stage since (1) we need to compile everything for this stage and (2) it is guaranteed to run on the same hardware as the nightly job.

1. Modify `Jenkinsfile` and `Jenkinsfile-nightly` to break out the `cmake` and `make` commands separately in their 'Microbenchmark' stages.
2. Create a new command that just builds the DBMS and writes the time to a file:
   ```
   sh 'cd build && /usr/bin/time -p -o build-time.txt make -j$(nproc) terrier'
   ```
   Note that you want to use the Debian [`time`](https://manpages.debian.org/stretch/time/time.1.en.html) command not the built-in bash command since this lets you easily write the output to a file.
3. Create a second command that builds the test of the system:
   ```
   sh 'cd build && /usr/bin/time -p -o build-time.txt make -j$(nproc) all'
   ```
4. Parse the `build-time.txt` file and extract the 'real' value (decimal seconds). Upload this to the website.

**Comment by lmwnshn** [comment]
Oh, missed this one the other day. We have this! Nice work yall
