### ISSUE TITLE
Python Test Harness: Add Support for Server Commandline Args in Config Files

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#1054]
We need the ability to set the commandline arguments that are passed to the server from the Python Test Harness' new JSON config files. This will allow us to run the server in different modes in Jenkins to make sure that we are testing everything. That this is different than passing in flags to OLTP-Bench (e.g., query mode) since this is specifying the runtime behavior of the server.

Once this is done, we should add additional runs of TPC-C using OLTP-Bench in the `Jenkinsfile` 'Test' stage with these different modes:

1. Pipeline Metrics: `-metrics_pipeline=true`
2. Disable Query Cache: `-use_query_cache=false`

Then we should add a TPC-C run with the WAL disabled (`-wal=false`) to provide us with the upperbound performance of the system. This should be in both `Jenkinsfile-nightly` ('Performance') and `Jenkinsfile` ('End-to-End Performance').

**Comment by lmwnshn** [comment]
Fixed by #1177.
