### ISSUE TITLE
Python Test Harness: Set # of Allowed Connections in DBMS for End-to-End Tests

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#1061]
The DBMS currently only allows for four unique network connections by default. This prevents us from getting correct scalability and performance measurements in the 'End-to-End' stages in our CI pipeline.

We need to pass in the `-connection_thread_count=<int>` flag to the DBMS when we start it in [test_server.py](https://github.com/cmu-db/terrier/blob/master/script/testing/util/test_server.py). We can just set it to be equal to the number of terminals that OLTP-Bench will use in each run (or just set it to **32** threads for now).

This can either be done in conjunction with #1054 or as a quick fix so that we can start collecting proper performance data more quickly.

**Comment by lmwnshn** [comment]
Fixed by #1177.
