### ISSUE TITLE
Python Test Harness: Run DBMS with RamDisk for OLTP-Bench Tests

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#1062]
When we invoke OTLP-Bench now in our Jenkins pipeline, we run the DBMS using whatever the default disk to store the WAL. The 'Microbenchmark' stage in the `Jenkinsfile` uses a RAM disk that is mounted on the benchmark machines.

We want to extend the `Jenkinsfile-nightly` OTLP-Bench runs to also include RAM disk runs. It can be exactly the same OLTP-Bench configurations that we have now, except it should pass the server the arguments `-log_file_path=/mnt/ramdisk/wal.log`. We may want to delete this file before each run.

We will also want to switch the 'End-to-End Performance' stage in `Jenkinsfile` to use the RAM disk as well.

This can be done as part of #1054.

**Comment by mbutrovich** [comment]
It's a string specifying a file path defined in settings_defs.h:

https://github.com/cmu-db/terrier/blob/master/src/include/settings/settings_defs.h#L93

The default is just "wal.log" when means it'll be placed where ever the current working directory is for running the binary. We override that to be `mnt/ramdisk/wal.log` to change the device it's writing to. In my opinion the name for the visualizations should reflect the _device_ being written to. So it should something like "RAM disk", "HDD", "SATA SSD", or "NVMe SSD" depending on the device being written to.

**Comment by bialesdaniel** [comment]
It looks like we can get some data from some linux tools but none of them quite look like `RAM disk`, `HDD`, etc. Does any of the data in this article look helpful? https://www.cyberciti.biz/faq/find-hard-disk-hardware-specs-on-linux/ Otherwise I think we would have to hard code it.

**Comment by bialesdaniel** [comment]
There is also `psutil.disk_partitions` https://psutil.readthedocs.io/en/latest/#disks I'm not sure if that is what we are looking for either

**Comment by lmwnshn** [comment]
Fixed by #1177.
