### ISSUE TITLE
compiler_test Suspected Race Condition

### ISSUE THREAD

**Issue by thepinetree** [cmu-db/noisepage#1086]
It looks like compiler_test is occasionally failing on various open branches as well as master. An investigation into where the race condition arises from is necessary. See the following Jenkins runs for details: 
- http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/642/tests
- http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1081/4/pipeline
- http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1067/22/pipeline

**Comment by lmwnshn** [comment]
I believe we only started seeing this after #1060 got merged.

**Comment by lmwnshn** [comment]
The Jenkins data got deleted for being too old. I _think_ it is the same as #1245 but I don't remember. Closing.
