### ISSUE TITLE
Join predicates which use inequalities are incorrect when using index joins

### ISSUE THREAD

**Issue by abalakumar083** [cmu-db/noisepage#1105]
Until Terrier adds functionality for specifying the join algorithm, reproducing this bug will be a bit contrived. But you can do the following,

```
CREATE TABLE xxx (id INT PRIMARY KEY, val INT);
CREATE TABLE yyy (id INT PRIMARY KEY, val INT);
INSERT INTO xxx VALUES  (3,3), (4,4), (5,5);
INSERT INTO yyy VALUES (3, 3), (4,4);
SELECT * FROM xxx INNER JOIN yyy ON xxx.val > yyy.val;
```

which produces the following correct output using a nested loop join: 
```
 id | val | id | val 
----+-----+----+-----
  4 |   4 |  3 |   3
  5 |   5 |  3 |   3
  5 |   5 |  4 |   4
(3 rows)
```
However, the following query,

`SELECT * FROM xxx INNER JOIN yyy ON xxx.id > yyy.id;` 

which should produce the same output, instead produces:
```
 id | val | id | val 
----+-----+----+-----
(0 rows)

```
because it uses an index join.

**Comment by apavlo** [comment]
@wgy8283335 Yes! If you want to look into go for it!

**Comment by wgy8283335** [comment]
@apavlo I'm very glad to do this. It will be my second contribution to the terrier project.
