### ISSUE TITLE
check_clang_tidy_extra.py is skipping files it shouldn't

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/noisepage#1120]
Related to #1119. #741 introduced an optimization that tries to make the `check-clang-tidy` target only run on files in that pull request's diff. However, clang-tidy issues have snuck into the master branch if you run it against the entire codebase. We should investigate this behavior and try to fix the issue so we don't introduce more clang-tidy failures in the future.

**Comment by lmwnshn** [comment]
Fixed by #1567.
