### ISSUE TITLE
What is the function of the package brain?

### ISSUE THREAD

**Issue by wgy8283335** [cmu-db/noisepage#1175]
I've read the codes in package brain. As there is no README in the package, I'm a little confused about the function of the package.  The function in package is called in CompilationContext::GeneratePlan(), as `auto features = recorder.RecordTranslators(pipeline->GetTranslators());`.
Why is the package called 'brain'? Is it a key part of self-driving system?

**Comment by apavlo** [comment]
@wgy8283335 Yes, it is part of the self-driving components. We can't discuss too much about it now because we are working on the paper.
