### ISSUE TITLE
Remove abort actions from bootstrap logic in DatabaseCatalog

### ISSUE THREAD

**Issue by jkosh44** [cmu-db/noisepage#1184]
Throughout the database catalog we register abort actions when adding the function context of builtin functions. An example is below. Doing so shouldn't be necessary because we assert that the transaction doesn't fail and if it did fail it would leave the DB in a non-functioning state.

However removing these lines causes a bunch of tests failures, the cause seems to be memory leaks. Some preliminary investigation seems to indicate that some tests rely on these abort actions to clean up memory.

We should remove these lines from the database catalog and fix the tests to not rely on them.

https://github.com/cmu-db/noisepage/blob/master/src/catalog/database_catalog.cpp#L2089-L2092

Brought up in #1139

**Comment by mbutrovich** [comment]
Do you recall which tests you saw failing?
