### ISSUE TITLE
Implement support for SHOW.

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/noisepage#1188]
Right now, we can SET settings to new values, but we can't easily check the current value of the setting without using a debugger. It would be nice to have SHOW. For only showing setting values, this should be similar to the existing code for supporting SET -- instead of calling `Set` you call `Get`.

**Comment by lmwnshn** [comment]
Whoever implements this, could you add tests for #1189? Thanks!

**Comment by apavlo** [comment]
We need this to support `SHOW TRANSACTION ISOLATION LEVEL` for the new version of OLTP-Bench
