### ISSUE TITLE
Unexpected code coverage decrease when adding support to nested queries

### ISSUE THREAD

**Issue by xinzhu-cai** [cmu-db/noisepage#1203]
#  Investigation Request
## Summary
In PR #1138, supporting new expressions and transformation rules led to unexpected code coverage drop. For example, adding a single line in comparison_translator.cpp led to -3.95% change.

We need to investigate why code coverage may decrease when adding new rules and new operators.

**Comment by apavlo** [comment]
We tested this and are able to prove that we are collecting coverage information correctly for SQL traces:

https://codecov.io/gh/cmu-db/noisepage/tree/PR-1204/src
