### ISSUE TITLE
DeferredActionManager: Unlink on a table that was already dropped

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/noisepage#1205]
## Summary
The DAManager freed a table that still had records to be unlinked from it.

## Environment
To address the bug, especially if it environment specific, we need to know what kind of configuration you are running on. Please include the following:

**OS**: Ubuntu 18.04 (LTS), Jenkins CI

**Compiler**: GCC 7.3

## Steps to Reproduce
1. Spotted in Jenkins [here](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1161/38/tests/).

It looks like the freeing of a table happens in the DAManager's backlog, but later there's still a GC operation to unlink a version from that table. The DAManager should process an action that is not safe to be processed. Unclear if this is a bug in the logic that enqueued the dropping of the table (needs another deferral?). It looks like it was a catalog table based on the stack trace for the initial allocation.

### Expected Behavior
Don't free a table before everything is unlinked.

### Actual Behavior
It freed a table before everything was unlinked.

**Comment by mbutrovich** [comment]
Jenkins log for posterity.
[jenkins.txt](https://github.com/cmu-db/noisepage/files/5285056/jenkins.txt)

**Comment by mush-zhang** [comment]
Is is possible that, abort actions are inserted into the deferred action queue usually earlier than pushing the txn context to the completed_txns_ . GC might be invoked twice between [abort_actions being pushed to deferred action queue](https://github.com/cmu-db/noisepage/blob/master/src/transaction/transaction_manager.cpp#L161) and the transaction being added to completed_txns. 
- abort_actions being pushed to deferred action queue
- GC thread loop process: the[ abort action ](https://github.com/cmu-db/noisepage/blob/master/src/catalog/database_catalog.cpp#L919)
