### ISSUE TITLE
TPC-H : Casting a string to date

### ISSUE THREAD

**Issue by gautam20197** [cmu-db/noisepage#1219]
# Feature Request
## Summary
For any query working on columns with data type date, there is no way to enter dates into the table or have predicates consisting dates. 
The main problem is the cast operator transform is missing in the system.

## Environment
I don't think it's an environment issue. But I'm running it on WSL2 on windows with Ubuntu 18.04.

## Steps to Reproduce
1. Compile with the following args: -DCMAKE_BUILD_TYPE=Release ..
2. Run terrier executable
3. Connect to the terrier terminal by executing : psql -h localhost -p 15721 -d terrier
4. Create the tables from "https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpch/ddls/tpch-postgres-ddl.sql" .
5. Run the query 

```SQL
select
        o_orderpriority
from
        orders
where
        o_orderdate >= date '1993-07-01'
        and o_orderdate < date '1993-10-01'


or 

select
        o_orderpriority
from
        orders
where
        o_orderdate >= '1993-07-01'::date
        and o_orderdate < '1993-10-01'::date

or 

select
        o_orderpriority
from
        orders
where
        o_orderdate >= TO_DATE('1993-07-01','YYYYMMDD');
        and o_orderdate < TO_DATE('1993-10-01','YYYYMMDD');

Error:
 what():  Code generation for expression type 'OPERATOR_CAST' not supported.
```

**Comment by mbutrovich** [comment]
Can you provide a more succinct `psql` sequence that manifests the issue so the person who works on this doesn't have to start with loading oltpbench tables to debug?

**Comment by gautam20197** [comment]
Sure I will update all the issues with specific commands to create the tables.
