### ISSUE TITLE
Add setting options for metrics sampling rate.

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/noisepage#1225]
We support sampling for metrics collection and right now the sampling intervals are hard-coded in the code, like [here](https://github.com/cmu-db/noisepage/blob/master/src/include/main/db_main.h#L734). We should add setting options for every type of metrics we have. For example, we could add a `pipeline_metrics_sample_interval` setting for the pipeline metrics. BTW, I prefer to change the `metrics_pipeline` setting to `pipeline_metrics` to be consistent with how we call that metrics in other places. Other metrics are similar.

**Comment by lmwnshn** [comment]
`pipeline_metrics_sample_rate` exists
