### ISSUE TITLE
Cast srting to float test fails in Jenkins

### ISSUE THREAD

**Issue by jkosh44** [cmu-db/noisepage#1253]
## Summary
Jenkins build failed: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1161/36/tests/ on sql_vector_operations_vector_cast_test. Right now it's unclear what the cause was and how to reproduce, but as I investigate I will fill in the details.

The PR where this came up is here: https://github.com/cmu-db/noisepage/pull/1161/files

## Environment

**OS**: macOS 10.14

**Compiler**: Clang 8.0. 

## Steps to Reproduce
I was able to reproduce by running the following commands on a mac
```
mkdir build
cd build
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DTERRIER_USE_ASAN=OFF -DTERRIER_BUILD_BENCHMARKS=OFF ..
ninja noisepage
cmake --build . --target sql_vector_operations_vector_cast_test -- 
./test/sql_vector_operations_vector_cast_test
```
Note: I had to wrap the test in a loop because it doesn't always fail. The way to make it fail is if there is an 'E' or 'e' in memory right after the `VarlenEntry`. There's no good way to force this scenario, so you just have to run it a bunch of times.

### Expected Behavior
Casting a string to a float should be successful

### Actual Behavior

- The cast throws an exception
- The cast is of type Double not Float
- The precision of the results are not what we expect

**Comment by jkosh44** [comment]
The test that failed was a test that casts a vector of Varchars to a vector of Floats.

The stack trace of the errors looks like this 
```
[ RUN      ] VectorCastTest.CastStringToFloat
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:171: Failure
Expected: signed char->Cast(exec_settings, TypeId::Float) doesn'unsigned short throw an exception.
  Actual: it throws.
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:173: Failure
      Expected: TypeId::Float
      Which is: 1-byte object <07>
To be equal to: signed char->GetTypeId()
      Which is: 1-byte object <0B>
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:175: Failure
      Expected: GenericValue::CreateFloat(-123.45)
      Which is: -123.449997
To be equal to: signed char->GetValue(1)
      Which is: '-123.45'
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:176: Failure
      Expected: GenericValue::CreateFloat(6.75)
      Which is: 6.750000
To be equal to: signed char->GetValue(2)
      Which is: '6.75'
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:178: Failure
      Expected: GenericValue::CreateFloat(0.8)
      Which is: 0.800000
To be equal to: signed char->GetValue(4)
      Which is: '0.8'
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:179: Failure
      Expected: GenericValue::CreateFloat(910)
      Which is: 910.000000
To be equal to: signed char->GetValue(5)
      Which is: '910'
[  FAILED  ] VectorCastTest.CastStringToFloat (0 ms)
[----------] 5 tests from VectorCastTest (1 ms total)
```

Breaking it down into individual failure scenarios we see
1. 
```
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:171: Failure
Expected: signed char->Cast(exec_settings, TypeId::Float) doesn'unsigned short throw an exception.
  Actual: it throws.

```
The error message seems really garbled for some reason but this refers to the expect found here: https://github.com/cmu-db/noisepage/blob/5264a0b9792ff40794a663d97e1c4d96f6033768/test/execution/sql_vector_operations_vector_cast_test.cpp#L171
The call to `Cast` should not have thrown an exception, but it did.

2.
```
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:173: Failure
      Expected: TypeId::Float
      Which is: 1-byte object <07>
To be equal to: signed char->GetTypeId()
      Which is: 1-byte object <0B>
```
This refers to this expect: https://github.com/cmu-db/noisepage/blob/5264a0b9792ff40794a663d97e1c4d96f6033768/test/execution/sql_vector_operations_vector_cast_test.cpp#L173
The result of the cast should have been of type `TypeId::Float`, which has an underlying value of 0x07. Instead it was of type `TypeId::Double` which has an underlying value of 0x0B.

3.
```
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:175: Failure
      Expected: GenericValue::CreateFloat(-123.45)
      Which is: -123.449997
To be equal to: signed char->GetValue(1)
      Which is: '-123.45'
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:176: Failure
      Expected: GenericValue::CreateFloat(6.75)
      Which is: 6.750000
To be equal to: signed char->GetValue(2)
      Which is: '6.75'
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:178: Failure
      Expected: GenericValue::CreateFloat(0.8)
      Which is: 0.800000
To be equal to: signed char->GetValue(4)
      Which is: '0.8'
/tmp/workspace/terrier_PR-1161/test/execution/sql_vector_operations_vector_cast_test.cpp:179: Failure
      Expected: GenericValue::CreateFloat(910)
      Which is: 910.000000
To be equal to: signed char->GetValue(5)
      Which is: '910'
```
These all seem to be related to the precision of the result of casts. We have seem similar issues in other parts of the system and other tests.

**Comment by jkosh44** [comment]
This test failure did happen on an intermediate commit of the PR in question (i.e. there were more commits made after this test failure before it was merged into master).
I'm not able to reproduce the test failures on my machine which is Ubuntu 20.04, gcc 9.3.0
I'm going to try to reproduce on a mac dev machine and also see if any other builds had a similar issue.

**Comment by jkosh44** [comment]
I was able to reproduce on a mac and updated the issue description. I was only able to cause the bug to happen by wrapping the test in a for loop suggesting that the failure is either non-deterministic or only happens when casting multiple times sequentially

**Comment by jkosh44** [comment]
The exception message that happens during cast is "Type VarChar cannot be cast because the value is out of range for the target type Float." This exception is thrown from here: https://github.com/cmu-db/noisepage/blob/be073e478e09de6738145d0d193308adfaee9d0e/src/include/execution/sql/operators/cast_operators.h#L48
It's still unclear to me why this ends up in a cast to double though.

**Comment by jkosh44** [comment]
After further investigation this is what I've found out. For a successful cast the following happens

1. `TryCast<storage::VarlenEntry, float>` is called to cast the string to a float 
https://github.com/cmu-db/noisepage/blob/ed86192c8ea5c7a075444888eefe833b8e398856/src/execution/sql/operators/cast_operators.cpp#L7-L13

2. This method first calls `TryCast<storage::VarlenEntry, double>` which converts the string to a double 
https://github.com/cmu-db/noisepage/blob/ed86192c8ea5c7a075444888eefe833b8e398856/src/execution/sql/operators/cast_operators.cpp#L15-L18

3. Then `TryCast<double, float>` is called to down cast the double to float 
https://github.com/cmu-db/noisepage/blob/ed86192c8ea5c7a075444888eefe833b8e398856/src/include/execution/sql/operators/cast_operators.h#L229-L254

However whenever the test is failing `TryCast<storage::VarlenEntry, double>` returns false and `TryCast<double, float>` is never called

This explains why we're getting the double, somehow the cast from string to double is actually successful, but `TryCast<storage::VarlenEntry, double>` still returns false.

**Comment by jkosh44** [comment]
Whenever the test fails, the false is coming from this function: https://github.com/cmu-db/noisepage/blob/ed86192c8ea5c7a075444888eefe833b8e398856/src/include/execution/util/fast_double_parser.h#L332-L467

Specifically this line: https://github.com/cmu-db/noisepage/blob/ed86192c8ea5c7a075444888eefe833b8e398856/src/include/execution/util/fast_double_parser.h#L404-L406

**Comment by jkosh44** [comment]
So I'm pretty sure I found the root cause of the bug. The reason is that the strings (`char *`) passed to `really_inline static bool ParseNumberBase(const char *p, double *outDouble)` are not null terminated. Now this normally wouldn't matter because the method returns once it hits a noninteger, EXCEPT if it hits an 'e' or 'E', presumably to handle exponent cases.
https://github.com/cmu-db/noisepage/blob/ed86192c8ea5c7a075444888eefe833b8e398856/src/include/execution/util/fast_double_parser.h#L395
It just so happens that if we add a print to the start of the method `std::cout << p << std::endl;` then this method returns false whenever the input happens to have an E after it. For example when `6.750EPl<FB>^?` is printed we will return false, but when `6.75pJPl<FB>^?` is printed we will return true.

**Comment by jkosh44** [comment]
Test can be consistently reproduced with this test: https://github.com/jkosh44/terrier/blob/855fc94aac4f3db5e175c4f028d0e7ff5cb949c9/test/execution/sql_vector_operations_vector_cast_test.cpp#L182-L197

**Comment by jkosh44** [comment]
The reason the strings are not null terminated is right here
https://github.com/cmu-db/noisepage/blob/d70c1c17b649abd9f6512c1715244553b3c1b140/src/include/storage/storage_defs.h#L278-L298
As far as I can tell the input `content` is always null terminated. But when we inline a `VarlenEntry` we only copy the characters of the string and not the null terminating character. So when `size == PrefixSize()` then we have no guaranteed that `prefix_`  will be null terminated.

The reason this is only happening on mac is probably just some quirk having to do with differences in the OS with regards to memory. I was able to generate similar behavior on Ubuntu by adding some random print statements

**Comment by jkosh44** [comment]
Additionally `fast_double_parser` is actually an external library found here: https://github.com/lemire/fast_double_parser
The specifically say 
> Like the standard C functions, it expects that the string representation of your number ends with a non-number character (e.g., a null character, a space, a colon, etc.). If you wish the specify the end point of the string, as is common in C++, please consider the fast_float C++ library instead.

So one possible fix is to replace `fast_double_parser` with `fast_float` found here: https://github.com/lemire/fast_float

**Comment by jkosh44** [comment]
Another possible fix is to only inline `VarlenEntry` when the size is one less than the prefix size. That way inlined strings will always be null terminated.

**Comment by mbutrovich** [comment]
> Another possible fix is to only inline `VarlenEntry` when the size is one less than the prefix size. That way inlined strings will always be null terminated.
> 
> Edit: I don't think this is actually a good solution.

`VarlenEntry` will never be null-terminated. That's why we have the size field. Everything else in the system expects no null-termination in the storage layer. Can the parsing method we're using take a length arg?

**Comment by pmenon** [comment]
Yes, switch to `fast_float`. It's a stop-gap until `std::from_chars()` supports float/doubles. We already use it for integer types.
