### ISSUE TITLE
Tracefile tests line 290 & 295 fail sporadically

### ISSUE THREAD

**Issue by bialesdaniel** [cmu-db/noisepage#1266]
# Tracefile Test Fail line 290 & 295

## Summary
Two of the tracefile tests failed in Jenkins but I was unable to reproduce it. http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/collect-microbenchmark-results/74/pipeline

## Environment
Run on Jenkins
**OS**: macos-10.14

**Compiler**: clang-8.0

## Steps to Reproduce
I have not been able to reproduce this failure. I am confident that this did not have to do with the code in my PR. It seems like it may have been a problem introduced elsewhere and just does not surface that often.

### Expected Behavior
I am not familiar with the tests so I am just posting the test output
```bash
INFO : [java] │        ├─ Line:290 | Hash:b6d55f2c7042fac31f69133143921bde ✘ Failure at Line 290: 
INFO : [java] │        │        SELECT * FROM part WHERE amount > (SELECT MAX(qty) FROM shipment WHERE shipment.pno = part.pno) order by pno;
INFO : [java] │        │        Query expected 21 results, got 21 results
INFO : [java] │        │        [1, 11, item_14, 1, 5, item_12, 1, 10, item_11, 2, 20, item_21, 3, 15, item_33, 4, 10, item_42, 5, 1000, item_51]
INFO : [java] │        │        [21 values hashing to b6d55f2c7042fac31f69133143921bde]
INFO : [java] │        │        expected: <b6d55f2c7042fac31f69133143921bde> but was: <634b5815f1cf014eda72b4ee73084fe4>[1, 11, item_14, 1, 5, item_12, 1, 10, item_11, 2, 20, item_21, 3, 15, item_33, 4, 10, item_42, 5, 1000, item_51]
INFO : [java] │        ├─ Line:295 | Hash:d3434eea5eea795c4f57399ca9e18e69 ✘ Failure at Line 295: 
INFO : [java] │        │        SELECT * FROM part WHERE amount < (SELECT MAX(qty) FROM shipment WHERE shipment.pno = part.pno) order by pno;
INFO : [java] │        │        Query expected 15 results, got 15 results
INFO : [java] │        │        [1, 1, item_13, 3, 2, item_32, 3, 5, item_31, 4, 2, item_43, 4, 4, item_41]
INFO : [java] │        │        [15 values hashing to d3434eea5eea795c4f57399ca9e18e69]
INFO : [java] │        │        expected: <d3434eea5eea795c4f57399ca9e18e69> but was: <9aa532fce87fd6e8596370e3885b74fa>[1, 1, item_13, 3, 2, item_32, 3, 5, item_31, 4, 2, item_43, 4, 4, item_41]
```

**Comment by apavlo** [comment]
@xinzhu-cai Can you look into this?

**Comment by lmwnshn** [comment]
We hit this quite often now, it seems. Always on a Mac.

**Comment by jkosh44** [comment]
Another instance of this issue: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1271/4/pipeline#step-270-log-699 (I think the line number changed)

**Comment by jrolli** [comment]
This appears to be caused by a poorly specified `ORDER BY` clause on these queries.  Specifically, `pno` is not a unique column (see line 100-146 of `nested_query.test`) and therefore does not guarantee any canonical ordering of the result set.  Using the error message from [1], it appears that the expected hash value uses `ORDER BY part_name`.
