### ISSUE TITLE
Testing: floating point precision causing trace file failures

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/noisepage#1284]
# Bug Report
## Summary
CI trace file tests causing false failures due to floating point precision differences.

## Environment
Jenkins CI.

## Steps to Reproduce
See: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1279/12/pipeline

### Expected Behavior
Trace file tests shouldn't fail for floating point precision differences.

### Actual Behavior
Trace file tests fail for floating point precision differences. See link above. If I'm reading that correctly, the results have the same raw values, but they hashed differently so the test failed.

**Comment by jrolli** [comment]
At first glance both of these errors are likely caused in part form underspecified sort orders (they have no `ORDER BY` clause).  Additionally, there appears to be some inconsistent application of whether floats should be cast to integers prior to hashing (which I think was the guard on floating point precision problems).

For line 141 failure:

Expected string: `2\n4\n2\n2\n1\n1\n` (md5: `c9ebc146b67fa6b443f8da2bbc9c9d8c`)

Checked string: `2\n1.000000\n1\n2\n4.000000\n2\n` (md5: `12b9658d138b7937e47a79ddd5f4fc47`)

(hashes derived by `echo -ne $STRING | md5sum`)

Relevant Java functions:
   `getHashFromDb` (`TestUtility.java:159`)
   `main` at hash check (`GenerateTrace.java:75-104`)

**Comment by mush-zhang** [comment]
After merging pr #1287 , the faiture still persists.

**Comment by jrolli** [comment]
#1287 does not fix the problem yet.  The initial patch did not fix all of the tests and after a discussion on Slack, the fix should address the sort issues in Java and not SQL.

**Comment by jrolli** [comment]
@mush-zhang, #1287 should now fix your problem.
