### ISSUE TITLE
jumbotest_execution_index_iterator_test fails on master

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1301]
# jumbotest_execution_index_iterator_test fails on master

## Summary
It seems that jumbotest_execution_index_iterator_test fails on master due to `malloc_consolidate(): invalid chunk size
`. Unsure what might cause that. jenkins build where it fails. http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/789/tests

## Environment
To address the bug, especially if it environment specific, we need to know what kind of configuration you are running on. Please include the following:

**OS**: Ubuntu 20.04 (LTS)

**Compiler**: Clang 8.0+.

**Comment by jkosh44** [comment]
Seems like this is either related to or a duplicate of https://github.com/cmu-db/noisepage/issues/1261

**Comment by eppingere** [comment]
yes it is
