### ISSUE TITLE
publish xUnit test report fails on jenkins

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1303]
# publish xUnit test report fails on jenkins

## Summary
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/783/pipeline/46/#step-151-log-1

## Environment
**OS**: macOS (whatever runs on jenkins)

**Compiler**: clang 8

**Build Type**: Release

**Comment by mbutrovich** [comment]
@crd477 fixed this already by changing the way Python on macOS nodes are managed in Jenkins.
