### ISSUE TITLE
JUnit crashes db?

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1305]
# JUnit crashes db?

## Summary
One some runs of JUnit the database exits and returns error code -6: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/790/pipeline

## Environment
To address the bug, especially if it environment specific, we need to know what kind of configuration you are running on. Please include the following:

**OS**: Ubuntu 20.04 (LTS)

**Compiler**: GCC 9.3 with release

**Comment by lmwnshn** [comment]
The log is gone, no idea what this bug was.
