### ISSUE TITLE
Wiki doesn't reflect name change to NoisePage

### ISSUE THREAD

**Issue by tanujnay112** [cmu-db/noisepage#1306]
Welcome to the issue tracker for **NoisePage**! We're excited that you're interested in improving our system. Below, please **choose either a Feature Request or Bug Report** and replace the sample text below to describe the issue! Additionally, please choose the appropriate labels on the Github panel. If you wish to and are able to solve the issue, feel free to assign yourself; otherwise we will manage this later!

The wiki still refers to Terrier, this should be changed with a quick find and replace.

**Comment by lmwnshn** [comment]
RIP wiki
