### ISSUE TITLE
Failed to bind networked socket in jumbo tests

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1318]
# Failed to bind networked socket in jumbo tests

## Summary
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/793/tests

## Environment

**OS**: Ubuntu 20.04 (LTS)

**Compiler**: GCC 9.3

**Comment by jkosh44** [comment]
I think this should have been fixed with https://github.com/cmu-db/noisepage/pull/1316

Is the failure from before or after that PR was merged?

**Comment by eppingere** [comment]
This failure seems to be from before? I will close. @jkosh44 feel free to reopen if it is not actually fixed
