### ISSUE TITLE
brew --prefix llvm@8 fails on jenkins

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1342]
# brew --prefix llvm@8 fails on jenkins

## Summary
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/803/pipeline

## Environment
To address the bug, especially if it environment specific, we need to know what kind of configuration you are running on. Please include the following:

**OS**: mac on jenkins

**Comment by mbutrovich** [comment]
@crd fixed this a couple of days ago. This was the solution, I think:
https://stackoverflow.com/questions/54848319/homebrew-broken-cannot-load-such-file-vendor-bundle-bundler-setup-loaderr
