### ISSUE TITLE
Race condition in GetFunctionContext

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/noisepage#1350]
Noticed this a couple of months ago and forgot to open an issue after following up with @tanujnay112. `DatabaseCatalog::GetFunctionContext` lazily bootstraps pg_proc. This was done to simplify recovery logic, but is a race condition if two threads call this method at once when the catalog isn't fully bootstrapped. Will it actually happen? Currently I don't think so, and I added an assertion in child calls in #1187 that should yell at us if it does. That said, it's a huge footgun, isn't documented as such right now, and we shouldn't be doing writes to catalog tables in a get method.

https://github.com/cmu-db/noisepage/blob/5efcc29e5d07b0fc5692ae25a4bd44264a5d474d/src/catalog/database_catalog.cpp#L2232

**Comment by jrolli** [comment]
I'm pretty sure #1344 will fix this.
