### ISSUE TITLE
Unsupported distribution 'CENTOS 7'

### ISSUE THREAD

**Issue by darionyaphet** [cmu-db/noisepage#1353]
Welcome to the issue tracker for **NoisePage**! We're excited that you're interested in improving our system. Below, please **choose either a Feature Request or Bug Report** and replace the sample text below to describe the issue! Additionally, please choose the appropriate labels on the Github panel. If you wish to and are able to solve the issue, feel free to assign yourself; otherwise we will manage this later!

seems NoisePage not support CentOS7

**Comment by thepinetree** [comment]
Hi there! We're glad you're interested in taking NoisePage for a test drive yourself! Unfortunately, we only officially support **Ubuntu 20.04** or **macOS 10.14+** at the moment.

**Comment by Zhangjindou1994** [comment]
i have installed the ubutu 20.04,but still encount the error like :
Unsupported distribution 'UBUNTU 20.04'
Please contact our support team for additional help.
Be sure to include the contents of this message.
Platform: Linux ubuntu 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

why?

**Comment by eppingere** [comment]
I'm not sure what is happening, but if you want to just do the install, you can put in a script and run:

```
LINUX_BUILD_PACKAGES=(\
  "build-essential" \
  "clang-8" \
  "clang-format-8" \
  "clang-tidy-8" \
  "cmake" \
  "doxygen" \
  "git" \
  "libevent-dev" \
  "libjemalloc-dev" \
  "libpq-dev" \
  "libpqxx-dev" \
  "libtbb-dev" \
  "libzmq3-dev" \
  "lld" \
  "llvm-8" \
  "pkg-config" \
  "postgresql-client" \
  "python3-pip" \
  "ninja-build"
  "wget" \
  "zlib1g-dev" \
  "time" \
)

LINUX_TEST_PACKAGES=(\
  "ant" \
  "ccache" \
  "curl" \
  "lcov" \
  "lsof" \
)

PYTHON_PACKAGES=(\
  "distro"  \
  "lightgbm" \
  "pandas" \
  "psutil" \
  "PTable"
  "pyarrow" \
  "pyzmq" \
  "requests" \
  "sklearn" \
  "tqdm" \
)

install_linux() {
  # Update apt-get.
  apt-get -y update
  
  # Install packages.
  if [ "$INSTALL_TYPE" == "build" -o "$INSTALL_TYPE" = "all" ]; then
    apt-get -y install `( IFS=$' '; echo "${LINUX_BUILD_PACKAGES[*]}" )`
  fi
  if [ "$INSTALL_TYPE" == "test" -o "$INSTALL_TYPE" = "all" ]; then
    apt-get -y install `( IFS=$' '; echo "${LINUX_TEST_PACKAGES[*]}" )`
  fi
  
  # Always install Python stuff
  # python3 -m pip --version || install_pip
  for pkg in "${PYTHON_PACKAGES[@]}"; do
    python3 -m pip show $pkg || python3 -m pip install $pkg
  done
}

install_linux
```

**Comment by apavlo** [comment]
@Zhangjindou1994 Can you post this as a separate issue?

**Comment by Zhangjindou1994** [comment]
I&nbsp; checked the packages.sh inlcuded in the&nbsp;noisepage-master.zip which i download from github,and i found shell text like this:
## TERRIER PACKAGE INSTALLATION
##
## This script will install all the packages that are needed to
## build and run the DBMS.
##
## Supported environments:
##&nbsp; * Ubuntu 18.04
##&nbsp; * macOS
## =================================================================

..........
&nbsp; &nbsp; &nbsp; # Check Ubuntu version
&nbsp; &nbsp; &nbsp; case $VERSION in
&nbsp; &nbsp; &nbsp; &nbsp; 18.04) install_linux ;;
&nbsp; &nbsp; &nbsp; &nbsp; *) give_up $DISTRO $VERSION;;
&nbsp; &nbsp; &nbsp; esac
&nbsp; &nbsp; &nbsp; ;;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmu-db/noisepage"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 凌晨2:27
收件人:&nbsp;"cmu-db/noisepage"<noisepage@noreply.github.com&gt;;
抄送:&nbsp;"张金豆"<504183723@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cmu-db/noisepage] Unsupported distribution 'CENTOS 7' (#1353)





 
@Zhangjindou1994 Can you post this as a separate issue?

**Comment by Zhangjindou1994** [comment]
My fault,it seems that the zip has been&nbsp; already upgraded




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmu-db/noisepage"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 凌晨2:27
收件人:&nbsp;"cmu-db/noisepage"<noisepage@noreply.github.com&gt;;
抄送:&nbsp;"张金豆"<504183723@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cmu-db/noisepage] Unsupported distribution 'CENTOS 7' (#1353)





 
@Zhangjindou1994 Can you post this as a separate issue?
