### ISSUE TITLE
E2E Performance wal_disabled does not actually disable the WAL (and other config-related bugs).

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/noisepage#1384]
# Bug Report

E2E Performance wal_disabled does not actually disable the WAL.

## Summary

`generate_server_args_str` does not translate `False` arguments faithfully, so any `.config` settings that are set to `False` will actually be ignored and set to whatever the default behavior in `noisepage` is.

This came up because @mbutrovich noticed that the performance of our TPCC numbers in E2E performance was:
`(Faster) tpcc_wal_ramdisk.json  >> tpcc_wal_disabled.json == tpcc.json (Slower)`

i.e., ramdisk faster than no wal is weird.

This probably affects the nightly stuff as well.

## Environment

Anywhere.

## Steps to Reproduce

1. Add this to `db_server.py` at the end of `NoisePageServer.__init__`:
```
        print()
        print("POTATO BANANA", self.server_args)
        print("POTATO DUCK", generate_server_args_str(self.server_args))
        print()
```
2. You should observe:
```
POTATO BANANA {'wal_file_path': 'wal.log', 'connection_thread_count': 32, 'wal_enable': False, 'record_buffer_segment_size': 10000000}
POTATO DUCK --wal_file_path=wal.log --connection_thread_count=32 --wal_enable --record_buffer_segment_size=10000000
```

Notice that the `False` is dropped. This is what gets passed to the `noisepage` binary.

**Comment by lmwnshn** [comment]
@bialesdaniel Whatever refactoring of Jenkins happens in #1368, I think at minimum it needs to go back to printing the actual bash commands that are getting invoked. I'm not familiar with the scripting side of stuff, it took at least ten minutes of bouncing around from `run_oltpbench -> constants -> test_case (whoops wrong file, backtrack) -> test_server -> db_server` to figure out what was actually being passed. If it was written in plain copy-paste bash, we probably would have spotted the error immediately.

**Comment by bialesdaniel** [comment]
Interesting. This seems to be a new bug based on this dashboard https://stats.noise.page/grafana/d/throughput_trends/throughput-trends?orgId=1&var-wal_device=None&var-benchmark_type=tpcc&var-terminals=All

**Comment by bialesdaniel** [comment]
@lmwnshn This is not related to the changes in #1368 I think it would be a separate PR

**Comment by lmwnshn** [comment]
@bialesdaniel Yea, I know. That's a note to say that due to the long stacking of abstract config files, we had no idea what was actually being run in Jenkins which led to this issue. To avoid a similar problem in the future, because your PR is trying to also config-ize Jenkins and abstract away stuff, I think it would be good for the code in #1368 to always make that that it is printing the actual bash commands that are getting invoked.

**Comment by apavlo** [comment]
@bialesdaniel Can we add a `--dry-run` flag that just prints the commands that would be executed?

**Comment by bialesdaniel** [comment]
> @bialesdaniel Yea, I know. That's a note to say that due to the long stacking of abstract config files, we had no idea what was actually being run in Jenkins which led to this issue. To avoid a similar problem in the future, because your PR is trying to also config-ize Jenkins and abstract away stuff, I think it would be good for the code in #1368 to always make that that it is printing the actual bash commands that are getting invoked.

Yes that makes sense. I implemented your suggestion to not use the cmake defaults and to actually always specify a value and I think that actually ends up also accomplishes printing the options cause it will show up in the Jenkins logs/ blue ocean steps

**Comment by bialesdaniel** [comment]
> @bialesdaniel Can we add a `--dry-run` flag that just prints the commands that would be executed?

@apavlo For dry run I think there are several steps that we could potentially include. I've listed them below along with my gut reaction of whether to include them.

1. Download OLTPBench (Don't include)
2. Start server (includes printing command that started the server), stop server (Do include)
3. Load data for OLTPBench test into database (Don't include)

**Comment by lmwnshn** [comment]
IMO I am inclined to include everything -- one line of output does not cost very much to print, relative to debugging the scripts.
