### ISSUE TITLE
Jenkins has issue pulling from github?

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1412]
# Jenkins has issue pulling from github?

It appears that jenkins has some issues pulling from github but only for the end to end performance? I've re-ran it it has happened twice in a row?

http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1394/21/pipeline/
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1394/22/pipeline/

It tries to clone from the `cmu-db/terrier.git` repo. Idk if that might be what is causing things.

Potential fix might be renaming your fork to noisepage???

**Comment by crd477** [comment]
I'm pretty sure this was related to a missing network configuration after a power outage and reboot on the benchmarker nodes.  I've fixed that now.
Please let me know if you still have the problem.

**Comment by lmwnshn** [comment]
Seems to be all good now.
