### ISSUE TITLE
No branch for CMU 15-721 course (e.g. 15721-s20-project2)

### ISSUE THREAD

**Issue by fzyzcjy** [cmu-db/noisepage#1418]
# Bug Report

## Summary

Hi thanks very much for the wonderful database and course (CMU 15-721)! It seems that the code related to CMU 15-721 course cannot be found... For example, in project 2 (https://15721.courses.cs.cmu.edu/spring2020/project2.html) we should write code using `git://github.com/cmu-db/terrier.git` (renamed to noisepage) with the branch `15721-s20-project2`. However, there is no such branch here...

## Environment
N/A

## Steps to Reproduce
Just look at GitHub :)

**Comment by rohanaggarwal7997** [comment]
The branches are kept only when the course is in session. Currently Dr Pavlo is not taking 15-721 in spring 2021.

**Comment by fzyzcjy** [comment]
@rohanaggarwal7997 Thanks very much!

Since CMU is well known for being friendly to students wanting to self-learn course materials, I wonder where I can get a copy of the old branch?

**Comment by rohanaggarwal7997** [comment]
You can recover old deleted branches 
https://docs.microsoft.com/en-us/azure/devops/repos/git/restore-deleted-branch?view=azure-devops

**Comment by fzyzcjy** [comment]
@rohanaggarwal7997 Sorry that seems to only apply to azure not GitHub...

**Comment by rohanaggarwal7997** [comment]
Then download the repo and do this
https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git

**Comment by fzyzcjy** [comment]
Thanks I will have a look (I originally thought there would be a official backup instead of these brute-force methods :) )

**Comment by fzyzcjy** [comment]
@rohanaggarwal7997 Hi sorry for the late reply. As I have expected, that stackoverflow answer only works if I have had the branch in the git repo (and have accidentially deleted it) - in that case it can be recovered. However, for Noisepage, it cannot be recovered... Following is the output:

```
git reflog --no-abbrev

958cc0b9a7d772898d50522b1216631476f448fc (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/cmu-db/noisepage
```

Therefore, I wonder whether someone has a copy of the old branch? Or, if you have worked with it, maybe you can discover that branch.

Thank you very much! The course looks very interesting and I cannot wait to learn it :)

**Comment by rohanaggarwal7997** [comment]
I don’t have it with me. I deleted all my branches recently. Probably @mbutrovich cab help you out ?

**Comment by mbutrovich** [comment]
I don't have it. Your best bet is probably to poke around forks and find a student who took the class that semester and hasn't kept their fork up to date. The branch will likely still be there.

**Comment by fzyzcjy** [comment]
Hmm thanks very much! Let me have a look.

**Comment by yurunyang1998** [comment]
> Hmm thanks very much! Let me have a look.

Hello, I am also been self-learning this course recently, and I meet the same problem as you, I can't find the project branch in this repo. Did you find an available branch?

**Comment by fzyzcjy** [comment]
@yurunyang1998 No. I finally used MIT 6.830 instead.

**Comment by yurunyang1998** [comment]
> @yurunyang1998 No. I finally used MIT 6.830 instead.

all right , thank you.

**Comment by fzyzcjy** [comment]
@yurunyang1998 You are welcome.
