### ISSUE TITLE
The status of this project: Production ready / beta / only as a toy?

### ISSUE THREAD

**Issue by fzyzcjy** [cmu-db/noisepage#1430]
# Feature Request
## Summary

Hi, I get to know this database when looking at CMU 15-721. I am quite curious about the current state of this db. The features sound quite promising! So I wonder whether it can be ready for production, or in beta or alpha test, or even only a toy?

## Solution
N/A

**Comment by apavlo** [comment]
This is a research project. It is not ready for production use. See our publication list to learn more:

https://noise.page/publications/
