### ISSUE TITLE
Deprecated tbb::reader_writer_lock

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/noisepage#1435]
The `tbb::reader_writer_lock` has been deprecated, and the `tbb` document suggestes to use `std::shared_mutex`:
https://github.com/wjakob/tbb/blob/master/include/tbb/reader_writer_lock.h#L44

There are lots of warning messages due to this deprecation when we compile the system, which has been annoying. For example, during this recent master build:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/853/pipeline/34
http://jenkins.db.cs.cmu.edu:8080/blue/rest/organizations/jenkins/pipelines/terrier/branches/master/runs/853/nodes/34/steps/139/log/?start=0

Should we switch `tbb::reader_writer_lock` to `std::shared_mutex` as the document suggests? I'm not sure whether there's any performance implication of this.

**Comment by turingcompl33t** [comment]
I wrote some spinlock benchmarks a while ago and just refactored them to reader-writer locks to compare `tbb::reader_writer_lock` and `std::shared_mutex` (code is [here](https://github.com/turingcompl33t/cpp-playground/tree/master/locks/rw-bench)). Definitely feel free to run them for yourself, but I observe that `std::shared_mutex` outperforms `tbb::reader_writer_lock` on throughput at all but the lowest levels of contention, and always exhibits lower latency. This isn't really that surprising considering `tbb::reader_writer_lock` purports to use busy-waiting exclusively, and it's pretty well-established that the Linux scheduler handles spin-loops worse than most schedulers.

I also just ran some TPC-C benchmarks on some AWS boxes to compare the two in the context of the entire system. Takeaway was that any performance impact of changing the lock implementation is drowned out by fluctuations between benchmarks., which again isn't that surprising considering we only use `SharedLatch` in a couple places.

All of that is to say, I think we should feel relatively confident in swapping in `std::shared_mutex`. If you agree, I already have the branch with the change made and can submit the PR.

**Comment by malin1993ml** [comment]
@turingcompl33t Interesting! Thanks for sharing this information! I think we would probably discuss the proper way to benchmark this as a team. But in the meantime, I don't see any problem with submitting the PR if you already have the code. At least we can run it through CI and test it under the performance-guard (though that probably has similar or even higher fluctuations as the AWS machines).

**Comment by turingcompl33t** [comment]
Sounds like a plan @malin1993ml, like you said it will be interesting to see what CI has to say about it.
