### ISSUE TITLE
Input validation for decimals.

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/noisepage#1440]
# Feature Request
## Summary

We currently don't handle invalid input correctly for decimals in #1434, from my `.psql_history`.

```
create table foo (a decimal(10,2));
insert into foo values ('a');
insert into foo values ('10.1.2');
\errverbose
```

We should also be able to cast decimals into strings/ints as necessary.

I tried hacking something up quickly but there are also errors earlier than the binder, perhaps at parse time?

Not going to touch it for now. Might be a good beginner task.

**Comment by KanchanPrasad** [comment]
I would like to try.

**Comment by lmwnshn** [comment]
It didn't merge.
