### ISSUE TITLE
Record metrics for ANALYZE query

### ISSUE THREAD

**Issue by jkosh44** [cmu-db/noisepage#1488]
# Feature Request
## Summary
https://github.com/cmu-db/noisepage/pull/1450 adds a new query type, ANALYZE. I'm mainly opening this for awareness so we can decide if we want to record metrics for ANALYZE or just ignore it.

https://github.com/cmu-db/noisepage/blob/9d7198e7bd7820eb6d548b675d564f73bf40bf9e/src/include/self_driving/modeling/operating_unit_defs.h#L111-L114

**Comment by malin1993ml** [comment]
Thanks, @jkosh44! I think we can ignore it. But @thepinetree is correct that we should directly document this in the code in `operating_unit_defs.h`.
