### ISSUE TITLE
pip cache for CI docker build?

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/noisepage#1541]
# Feature Request

## Summary

If I'm reading the logs correctly, we're downloading large packages like `sklearn` and `torch` from pip every time on every CI node that does `packages.sh all`. This is probably a bit unfriendly to pip and is also an extra 10-15 minutes (2-4 minutes * number of top-level stages) that we could shave off build time.

## Solution

I'm not familiar with what's new in docker build caching. Buildkit, etc? This isn't a huge issue but would be nice to fix.

**Comment by crd477** [comment]
I can take this if you'd like.

**Comment by lmwnshn** [comment]
@crd477 If you have the time, that would be great! :)

**Comment by crd477** [comment]
OK, this is done.  The `packages.sh all` step appears to consistently take around 15 seconds now.

To date, I've just been manually doing this image update process periodically.  I really should get around to doing it in a more easily repeatable Docker-centric way.  Feel free to either close this issue now based on the immediate concern or leave it open as a reminder to me to automate the builder image process.

**Comment by lmwnshn** [comment]
Awesome, thanks! I'll just close the issue for now.
