### ISSUE TITLE
Add NoisePage to ClickBench

### ISSUE THREAD

**Issue by alexey-milovidov** [cmu-db/noisepage#1645]
# Feature Request
## Summary

[ClickBench](https://github.com/ClickHouse/ClickBench) is an open-source benchmark suite for analytical DBMS.
It already contains a wide range of DBMS and NoisePage will be a nice addition to it.
I think it can also facilitate system development.

## Solution

Here is the instruction: https://github.com/ClickHouse/ClickBench/blob/main/README.md#how-to-add-a-new-result

### Alternatives

[README](https://github.com/ClickHouse/ClickBench/blob/main/README.md) provides a comprehensive list of alternatives.

**Comment by alexey-milovidov** [comment]
@apavlo, the last commit in the repository is from one year ago - is it abandoned?

**Comment by apavlo** [comment]
@alexey-milovidov Yes, we pivoting to Postgres for the self-driving operation.
