### ISSUE TITLE
Change LargeTransactionTestObject to be initialized by a builder

### ISSUE THREAD

**Issue by tli2** [cmu-db/noisepage#195]
The constructor on this object has become quite bloated now that we have pushed so much functionality into it. Writing all these different implementations into one class is also getting out of hand, but we will need to add functionality to it in the near future to support interleaved inserts, deletes and sequential scans.

The first step to cleaning this up is to change the way we initialize the test object to be via the [Builder Pattern](https://en.wikipedia.org/wiki/Builder_pattern), cutting down the code clutter. Declare a `LargeTransactionTestBuilder` object where we can set these parameters via method (preferably self-reference return type for chaining). Pick reasonable default values for things we don't always care about.

Once this is done, it also becomes easy for us to actually return different dynamic types in the builder depending on the initialization parameters, making it possible to separate some code out from the current class.

**Comment by apavlo** [comment]
@tanujnay112 You can take a look at this.
