### ISSUE TITLE
Automated benchmark suite can run more configurations

### ISSUE THREAD

**Issue by tli2** [cmu-db/noisepage#212]
There's no reason why we have to pick a single thread number for concurrent benchmarks. Since we run benchmarks on a fixed server, we can do a mini scalability-test by running them for (1, 2, 4, 8, 16...) threads.

Not really a priority but good-to-have. The benchmarks run fast these days anyway.

**Comment by mbutrovich** [comment]
I'm not convinced that makes sense for per-PR continuous integration testing. We're looking for performance regressions and I suspect we'll spot it in either the single thread tests or fixed multithreaded tests we run.

What you're describing sounds more like a component of the nightly benchmarking.

**Comment by tli2** [comment]
We can do that too

**Comment by lmwnshn** [comment]
We do some form of scalability testing on stats.noise.page now.
