### ISSUE TITLE
Benchmark performance tracking and pass/fail

### ISSUE THREAD

**Issue by pervazea** [cmu-db/noisepage#215]
In issue #211 there is some discussion of a recent "regression" in benchmark performance, introduced by PR #200. The change introduced, was to the configuration of benchmark execution.

First, design goals and information:

1. My goal on the benchmark script was to minimize manual tracking and adjustments, as much as possible. Therefore keeping reference values for each benchmark was not desirable. Rather, we compute  an average from available history. Where no or insufficient history is available, we are liberal in pass / fail. (Trying to manually record and update reference numbers might work for a few benchmarks, but won't scale)

1. When we hit the first performance change, I implemented a quick fix to limit how much history to use. This is encoded in the benchmark execution script. The real fix requires quite a bit more work, and how to do it was not clear at the time.

Desired characteristics:
1. History limits need to be configurable via the Jenkins web interface in some way, and need to be configurable per benchmark.
1. Limits should be defined, ideally, by PR. (The quick fix used the only convenient metric at the time, which was build #. This is not user friendly, to say the least).

 Approach:
1. Jenkins has a facility for creating configuration files, that may be suitable for our needs. 
1. The history is taken from the nightly builds. These contain no readily accessible PR information. PR history is recoverable from Jenkins from the terrier repo, and could be correlated with nightly builds. 
1. The portion of the script that retrieves and processes history, needs reworking, in order to handle the required level of flexibility. 

This hasn't been an urgent issue, but I'll move it up in the priority list.

**Comment by lmwnshn** [comment]
We do (or did) track benchmark performance. The microbenchmarks just ended up being too noisy.
