### ISSUE TITLE
Future Parser

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/noisepage#234]
In the interests of having a working parser, we're currently porting over Peloton's parser. All we're doing is tidying up the files and imposing a bit more structure on it (e.g. previously almost all members were public, we at least make them const now).

We want to be Postgres-compatible, so we:

1. use libpg_query to generate Postgres C structs
2. have a lot of code that transforms the C struct into our own C++ class equivalents(*)
3. then hand off the C++ classes to whatever

(*) Currently, it is transformed/copied. It is NOT wrapped. There is no real good reason for this, but the effort of fixing it properly is on par with a rewrite.

There are some design problems with our old approach, which we're porting over.

1. Maintainability. We don't know if we're porting the C structs completely (we currently definitely don't). Previously we relied on comments // TODO: doesn't support x,y,z.
2. Outdatedness. @pervazea pointed out that we're never using the actual gram.y. Instead of going gram.y -> our layer, it goes gram.y -> generated code -> our layer. Ideally we'd be working with gram.y directly.
3. Inefficiency. There's currently no compelling reason to create the C structs at all.

In the future, we will definitely want a better/more complete parser. That probably involves throwing away **everything** we have right now.

Going forward, some options:

1. patch their grammar file, kind of like how libpg_query does it
2. write our own grammar file
  - antlr has much cleaner syntax (language-independent), but was cited to be slow
  - yacc is basically a macro system, so you end up with C++ code sprinkled in there - can be hard to maintain
3. wrap the generated C structs completely instead of reconstructing them as C++ classes

In the meantime, we'll keep porting the current parser over.

**Comment by mrzzzrm** [comment]
I don't know if fits you at all, but have you considered https://github.com/hyrise/sql-parser/? This parser is nowhere as feature rich as Postgres', but it's pretty decent, e.g., TPC-H is fully supported - and it emits an AST consisting of C++ objects. It's based on bison/flex as well, so if specific SQL language elements are missing, it's probably straight forward to port them from the postgres grammar. 
There is a basic usage example in the projects README.md, also see [here](https://github.com/hyrise/hyrise/blob/95561eca450cac55abc696e0c74be01bd68998ac/src/lib/sql/sql_translator.cpp#L264) for how Hyrise crawls the AST and translates it into a logical plan.

**Comment by lmwnshn** [comment]
Sorry for the late reply. I think we've stopped focusing on the parser temporarily, and also that we wanted to maintain full Postgres compatibility, @apavlo ?

**Comment by lmwnshn** [comment]
I doubt anyone is going to work on this. I would like to yoink DuckDB's improvements to our parser's structure, some day.
