### ISSUE TITLE
Differentiate DataTable * to SqlTable * 

### ISSUE THREAD

**Issue by tli2** [cmu-db/noisepage#259]
Up until now we have been using `DataTable *` most of the places for logging and GC purposes. This will need to change with indexes implemented since GC will potentially access the index and logging the SQL level schema to determine serialization format.

We need to eventually bite the bullet and go over all the `DataTable *` in various places to determine if they should really be `SqlTable *`. Also now that this is going on, maybe we really should rename `DataTable` to really reflect its nature as a transactional byte store with no notion of indexes or SQL concepts, but that's not as important.

**Comment by lmwnshn** [comment]
I'm not sure if we still want to go with the `SqlTable` abstraction - @jrolli is looking into some of this compiled storage accessor stuff, I believe. In light of that, probably close this?
