### ISSUE TITLE
Historical performance data

### ISSUE THREAD

**Issue by pervazea** [cmu-db/noisepage#266]
We have:
- benchmark runs integrated into Jenkins
- a script that compares current performance with historical performance, so we can catch regressions

The limitations of what we have include:
- Limited history. We delete old builds on Jenkins (after 30 days I believe). Regardless of the actual number, even if we kept the builds longer, we'd still want to have a time limit, as the builds and logs take significant space.
- No easy visualization of history.

What we could do:
1. Create a web server to provide visualization of the performance data.
2. Have the web server collect performance data from Jenkins, and store just the performance data in a database. This would allow us to keep as much history as we wanted, probably keep it for the life of the project. 

Both the above items would be a suitable project for someone. A while ago I posted some visualization (keep scrolling down for the images, and again for further comments):
![benchmarks_bar](https://user-images.githubusercontent.com/34660288/49760665-08a19780-fc93-11e8-80ab-691d974a1496.png)
For item 1, I used (Python) Django, from which the bar charts are generated. This could be extended.
For item 2, design and implementation is needed. This could be added to the existing code for item 1).

**Comment by pervazea** [comment]
See also, wiki page, [Microbenchmarks, Dashboard and Jenkins](https://github.com/cmu-db/terrier/wiki/Microbenchmarks%2C-Dashboard-and-Jenkins)

**Comment by lmwnshn** [comment]
stats.noise.page has some of this now.
