### ISSUE TITLE
Add latency measure to micro-benchmarks

### ISSUE THREAD

**Issue by pervazea** [cmu-db/noisepage#319]
(Possibly more than just micro-benchmarks).

We have a micro-benchmark suite that measures throughput of various operations.
In general, we also want to be measuring latency of those operations. 

The simple minded view of this. If the system queues requests at any place, we could have high throughput, high efficiency in terms of keeping CPUs fully occupied, but high latency as requests sit until they are able to be serviced.

**Comment by lmwnshn** [comment]
Latency is added to stats.noise.page, which is probably good enough.
