### ISSUE TITLE
Optimizer Task ASAN failure [in Peloton] (by query rewriting group)

### ISSUE THREAD

**Issue by 17zhangw** [cmu-db/noisepage#332]
After our team's discussion with Andy this morning, we were told to create an issue concerning an ASAN-related test failure in the old Peloton codebase here. 

We ran the Peloton tests with 2 minor additions to `TopDownRewrite::Execute` and `BottomUpRewrite::Execute` (adding a `rule->Check` call) that are described in the attached patch. We did not violate the documented precondition to `rule->Check` since (1) we used the expression returned by `GroupExprBindingIterator` which only returns structures that match the pattern; (2) the original code directly invoked `rule->Transform` which expects the "before" structure to be correct.

The steps for reproducing are as follows:
[1] Clone the Peloton git repo at origin/master (484d76df9344cb5c153a2c361c5d5018912d4cf4)
[2] Modify CMakeLists.txt to add `-faligned-new` to compile with GCC7.3.0
[3] Add `rule->Check()` to `TopDownRewrite` and `BottomUpRewrite` (refer to patch)
[4] Run `cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_SANITIZER=Address ..`
[5] 
Run `make -j32 index_scan_sql_test && ./test/index_scan_sql_test` OR
Run `make -j32 optimizer_sql_test && ./test/optimizer_sql_test` OR
Run `make -j32 check`
The ASAN error logs alongside the patch are attached.

According to the git blame, this part of `optimizer_task.cpp` was written by Bowei. 

Was there a particular reason, design choice, or usage assumption for why the original `TopDownRewrite` and `BottomUpRewrite` did not invoke `rule->Check` whereas `ApplyRule` did?

[index_scan_sql_test_dump.txt](https://github.com/cmu-db/terrier/files/3035744/index_scan_sql_test_dump.txt)
[optimizer_sql_test_dump.txt](https://github.com/cmu-db/terrier/files/3035797/optimizer_sql_test_dump.txt)
[make_check_dump.txt](https://github.com/cmu-db/terrier/files/3035827/make_check_dump.txt)
[patch.txt](https://github.com/cmu-db/terrier/files/3035742/patch.txt)

**Comment by mbutrovich** [comment]
@17zhangw says not relevant anymore.
