### ISSUE TITLE
OperatorExpression/AbstractExpression Interface (by query rewriting group)

### ISSUE THREAD

**Issue by 17zhangw** [cmu-db/noisepage#333]
This issue stems from our group's discussion with Andy this morning. 

As part of our query rewriting project, our group templatized several parts of Peloton's optimizer (which will be ported over some time in the near future) to allow those components (i.e Memo, Group, GroupExpression) to be able to work with both [Operator](https://github.com/cmu-db/peloton/blob/master/src/include/optimizer/operator_node.h)/[OperatorExpression](https://github.com/cmu-db/peloton/blob/master/src/include/optimizer/operator_expression.h) and AbstractExpression.

Our primary issue is that the AbstractExpression (even in terrier) and Operator/OperatorExpression (based on Peloton master) do not expose a consistent interface for the templatized components to use. In part, this is due to AbstractExpression being made immutable whereas the Operator/OperatorExpression (as is in Peloton) are mutable.

At the moment, we have a thin wrapper around AbstractExpression that emulate the functionality provided by Operator/OperatorExpression. However, in the long run, it would be much better if the two interfaces could be reconciled, along with how the optimizer components use them (i.e whether optimizer components, such as Memo; Group; GroupExpression; Binding; and others, create new objects each time or mutate existing ones).

**Comment by lmwnshn** [comment]
Do you mean that you need mutable expressions? If so, could you provide an example of how you're mutating them? (change their children, change the value in ConstantValueExpression, ...)

**Comment by 17zhangw** [comment]
Our current implementation requires changing the children. However, our group is currently working on creating a better abstraction layer, so it might better if this issue is put on hold for now.

**Comment by lmwnshn** [comment]
From what I remember, parser expressions are immutable because the idea was "we parse stuff, we ship it to the binder/optimizer, they rewrite it into plan nodes". We wanted to avoid possible bugs from Peloton where you're not sure if your expression is currently valid or not.

**Comment by mbutrovich** [comment]
@17zhangw says not relevant anymore.
