### ISSUE TITLE
Make pools dynamic

### ISSUE THREAD

**Issue by pervazea** [cmu-db/noisepage#346]
This applies to:

- RecordBufferSegmentPool
- BlockStore

There may be other structures too, that are built on top of ObjectPools. 

These are used in tests, where it is ok that they are statically sized provided there are a understood and bounded number of operations.

Instances are declared in:

- main.cpp
- catalog_sql_table.h

In these cases, the static sizing needs to be changed. Probably what we want, is for these sizes to be initially taken from the settings manager. The sizing should be runtime adjustable so that the self-driving components can tune the system appropriately. Increasing values is usually easy. Taking resources away can be complex.

**Comment by lmwnshn** [comment]
Closing this unless anyone objects.
