### ISSUE TITLE
Planner Directory Structure

### ISSUE THREAD

**Issue by GustavoAngulo** [cmu-db/noisepage#355]
With the nearly finished port of plan nodes (#312), we discussed in the weekly meeting how we want to organize the directories involved in the terrier planner. #312 will create the `src/planner` directory, where the plan nodes will live under `src/planner/plannodes`. Currently, the other planner directories are:
```
src/parser
src/parser/expression
```

When #312 is merged, these should be moved to:
```
src/planner/parser
src/planner/expressions
```

**Comment by wgy8283335** [comment]
@apavlo hi, is the issue still needed to be contributed? 
For this issue, what should I do is moving source code and unit test code from parser to planer, right?

**Comment by lmwnshn** [comment]
Just going to close this issue.
