### ISSUE TITLE
Restore AbstractExpression Meta-Data

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#420]
@mush-zhang found that the Peloton `TupleValueExpression` has an internal triple of `oid_t` called the `bound_obj_id`:

https://github.com/cmu-db/peloton/blob/master/src/include/expression/tuple_value_expression.h#L193

We did not port this over to the new repo. It is not clear what it is but it is likely that the optimizer needs it.

We need to investigate (1) what it is, (2) how it is being set, and (3) how it is being used. If we decide that we still want it, then we should port it over.

-----------

## Update: 2019-06-14

There are four different internal data members that we need to add back to the expressions:
1. `expr_name`
2. `depth`
3. `alias`
4. `has_subquery`

We think that we can get back `alias` by adding back in this line:

https://github.com/cmu-db/terrier/blob/master/src/parser/postgresparser.cpp#L778-L783

The `depth` and `has_subquery` values can be derived in the binder, but we are not sure just yet how to do this in a single pass through the expression tree.

**Comment by 17zhangw** [comment]
This line may provide some insight: https://github.com/cmu-db/peloton/blob/master/src/include/expression/tuple_value_expression.h#L157

**Comment by mush-zhang** [comment]
I am letting the postgres parser to write the alias to TupleValueExpression **only** in ColumnRefTransform() function. 
The `alias` field comes from the `ResTarget.name` in pg_parser. As its comment suggested, `name` is either:
1. column label in SELECT target list;
2. destination column in INSERT target-column-names list
3. destination column in UPDATE target list
Only column reference in select statement is stored as list of abstract expression, so I think that is the only place we need to call the constructor with `alias`. ( columns are stored as strings in INSERT and UPDATE)

**Comment by lmwnshn** [comment]
This made it in.
