### ISSUE TITLE
Need a way to inject test parameters in SettingsManager

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#430]
Right now we are only able to create `SetingsManager` entries at compile time:

https://github.com/cmu-db/terrier/blob/master/src/include/settings/settings_defs.h

The problem with this is that it is not possible to create synthetic parameters from testing code that we can use to check failure scenarios. In particular, we need to be able to inject faults in the action callbacks.

**Comment by lmwnshn** [comment]
(This was more about wanting settings lambdas)
