### ISSUE TITLE
Rename Action -> Event in deferred actions framework

### ISSUE THREAD

**Issue by tli2** [cmu-db/noisepage#443]
@mbutrovich pointed out that `Action` is an overloaded term in our system and using it here is ambiguous.

Not going to change relevant PR #441, as that increases the scope of the PR.

Also open to other names if you think they are better.

**Comment by apavlo** [comment]
What about `mevent`? As in a "memory event"?

**Comment by tli2** [comment]
I feel like nobody will know what that is, and this is not exactly restricted to just memory related actions. The prime example for this is in the compactor, deferred actions are used to requeue a block if no compaction took place.

I still think this is fundamentally an "action" and not an "event". On the other hand, "action" is an overloaded term, particularly in our system. So going down the thesaurus: task, job, chore, errand?
`Chore` might be an interesting name ...

**Comment by lmwnshn** [comment]
Paper got published, name probably isn't changing.
