### ISSUE TITLE
Change HashUtil::Hash() API

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#449]
The current `HashUtil::Hash()` helper method takes in an object reference without a length:

https://github.com/cmu-db/terrier/blob/master/src/include/common/hash_util.h#L84

We should switch it so that you explicitly have to pass in an object length. This will prevent people from abusing it.

To avoid have to change a bunch of existing code, we can create a bunch of specialized methods for common primitive types:

* `hash_t HashUtil::Hash(const bool &val)`
* `hash_t HashUtil::Hash(const int8_t &val)`
* `hash_t HashUtil::Hash(const int16_t &val)`
* `hash_t HashUtil::Hash(const int32_t &val)`
* `hash_t HashUtil::Hash(const int64_t &val)`
* `hash_t HashUtil::Hash(const float &val)`
* `hash_t HashUtil::Hash(const double &val)`

This should be part of the same group of fixes in #407 .

**Comment by tli2** [comment]
I think a much simpler fix would be to simply delete the templated function's body. Alternatively, we can move the body into a .cpp file.

This way, the API stays the same, but to call the function, a manual specialization is required that does the right thing. (Or an instantiation in the latter case)

**Comment by lmwnshn** [comment]
We refactored the `HashUtil` class to incorporate some of Prashanath's `enable_if` stuff. It does automatic specializations for arithmetic and string types. Maybe @apavlo can weigh in, but otherwise closing issue for now.
