### ISSUE TITLE
ParameterOffset Type

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#457]
A parameter offset is when you have a prepared statement with placeholder variables that are filled in at run time:

```sql
PREPARE my_stmt AS SELECT * FROM xxx WHERE id = $1;
```

For this query, the `WHERE` clause contains a `ParameterValueExpression` with the value idx of `0`. This is then used at runtime to get the value to fill in from the query's parameter array in its execution context.

In Peloton, there was an explicit type for keeping track of parameter offsets:

https://github.com/cmu-db/peloton/blob/master/src/include/type/type_id.h#L21

But right now the `ParameterValueExpression` represents the value idx field as a `uint32_t`:

https://github.com/cmu-db/terrier/blob/master/src/include/parser/expression/parameter_value_expression.h#L59

I first think that we should have an explicit type to represent parameter offsets. I think we can all agree on that.

But the question is what *kind* of type should this be. Should it be a C++ strong type (like `catalog::db_oid_t`) or should it be part of the value type system?

The problem with making it a C++ type is that there is code in the optimizer that treats the parameter value type as any other value in the DB's type system (e.g., like a `ConstantValueExpression` value):

https://github.com/cmu-db/terrier/blob/optimizer/src/optimizer/rule_impls.cpp#L349-L352

So if we make it a C++ type, then this code won't work without wrapping it in `TransientValue`. Truth be told I don't even know whether that particular snippet of code is correct.

I propose that we make it a C++ type and then see whether @17zhangw can fix things in the optimizer.

**Comment by 17zhangw** [comment]
@apavlo Is there any update on this issue?

Here is a stable link to the referenced L349-352 of `rule_impls.cpp` as referenced above: https://github.com/cmu-db/terrier/blob/151ca26e06fbf710da0d48ec299d38150274059d/src/optimizer/rule_impls.cpp#L349-L352

I would say that we still need a `type::TypeId::PARAMETER_OFFSET` for `TransientValue` to use so the execution engine would be able to identify that it is actually a parameter offset.
