### ISSUE TITLE
Codify OutputSchema for INSERT/UPDATE/DELETE PlanNodes

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#471]
We need to decide on what the `OutputSchema` contents look like for `InsertPlanNode`, `UpdatePlanNode`, and `DeletePlanNode`. It appears that this aspect of the execution engine was ad-hoc and not thought through in the Peloton codebase

I believe that the output of these PlanNodes should be exactly as their input. That should be enough for us to then be able to produce the expected status message for the Postgres wire protocol (e.g., the # of tuples inserted). I can't think of any reason where we would need to materialize the entire tuple (which would be expensive for deletes or updates that only modify a subset of a tuple's attributes).

**Comment by lmwnshn** [comment]
OutputSchema for INSERT/UPDATE/DELETE are empty. We track number of tuples through StorageInterface.
