### ISSUE TITLE
Correctly parse expression alias

### ISSUE THREAD

**Issue by mush-zhang** [cmu-db/noisepage#477]
Currently, terrier postgresparser only correctly handles alias of TableRef object and ColumnValueExpression object. We should make it correctly parse in the alias of any Expression types. 
One possible approach is to make postgres parser a friend of abstract expression, so that it can directly set the alias value. Refer here for how peloton sets the alias of any type of expression in the select list. https://github.com/cmu-db/peloton/blob/master/src/parser/postgresparser.cpp#L578
Or you may consider changing constructors for expresssion objects to take in another parameter alias.

**Comment by mush-zhang** [comment]
Sorry for missing that when I added in `alias` ...

**Comment by apavlo** [comment]
The following query is what fails:

```sql
CREATE TABLE B (b1 INT PRIMARY KEY, b2 INT);
SELECT b1+1 AS b1 FROM B
```

**Comment by lmwnshn** [comment]
I don't remember when we fixed it, but we did.
