### ISSUE TITLE
Add a cast check to CastManagedPointerTo

### ISSUE THREAD

**Issue by GustavoAngulo** [cmu-db/noisepage#487]
We should add a compile time assert to `ManagedPointer::CastManagedTo` that checks that users actually cast a class to a derived class, and not some random class. Something like [`std::is_convertible`](https://en.cppreference.com/w/cpp/types/is_convertible) inside a `static_assert` should handle this check. We should also consider renaming the method to something like `CastToDerived`.

**Comment by 17zhangw** [comment]
If it's sole purpose is to do a _downcast_ to a derived class, [std::static_cast](https://en.cppreference.com/w/cpp/language/static_cast) which provides a compile-time check or [std::dynamic_cast](https://en.cppreference.com/w/cpp/language/dynamic_cast) which provides a runtime check.

**Comment by lmwnshn** [comment]
I do not remember looking into this, so I'm unassigning myself. This probably involves a few hours of digging into arcane C++ incantations to find the right assertion.
