### ISSUE TITLE
Properly use ManagedPointer throughout the system

### ISSUE THREAD

**Issue by GustavoAngulo** [cmu-db/noisepage#489]
During our ManagedPointer call, we decided on the following things we need to resolve for each component:
* Resolve #424, a lot of the changes below will need this function 
* Parser (@lmwnshn)
  * Replace usages of shared_ptr
  * Parser should return a vector of all abstract expressions it created. It is the role of whoever calls the parser to defer deletion of these expressions since the parser has no concept of a transaction.
  * SQLStatements do not own expressions. Something similar to the above needs to be done for the SQLStatements, they should contain a vector of expressions they hold.
* Binder (@mush-zhang) 
  * Replace usages of shared_ptr in binder and logical operators. In general, the code pattern to use should be storing things as a `std::unique_ptr`, and getter methods return a `ManagedPointer`

* Optimizer + Plan Nodes (@17zhangw)
  * Expressions generated by the optimizer should be registered for deferred deletion
  * Replace usage of shared_ptr and have managed pointers in the plan nodes (I believe I did some of this in #386)
  * Deletion of plan nodes should be left up to whoever calls the optimizer

**Comment by lmwnshn** [comment]
Me, @mush-zhang, and @17zhangw think we did this.
