### ISSUE TITLE
clang-tidy: bugprone-macro-parentheses

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/noisepage#504]
We currently have this check disabled. However it should be re-enabled and the associated fixes should be applied to the codebase. I believe it mostly comes down to wrapping macro args in parentheses.

**Comment by tli2** [comment]
It was explicitly disabled for use cases like https://github.com/cmu-db/terrier/blob/a5b67df0a418aa9bae8bc6bd8469d24a04cea4d9/src/network/connection_handle.cpp#L46, where we are using macros for code generation and extra parens are semantic-changing.

If you explicitly NOLINT those it will probably be fine. But then I suspect that's a lot of NOLINTS.

**Comment by lmwnshn** [comment]
From a couple of minutes adding `/* NOLINT(bugprone-macro-parentheses) */` to macro-defined classes, I'm inclined to think that this one isn't worth it.

**Comment by lmwnshn** [comment]
bonk
