### ISSUE TITLE
TPCC test: bwtree memory leak

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/noisepage#544]
I spent some time chasing the infrequent tpcc_test failures on Jenkins. Looks like we still have a memory leak in the bwtree. I had to bump scale factor to 8 and increase number of transactions per worker to 100,000 on dev4. Log attached.
[tpcc_asan.txt](https://github.com/cmu-db/terrier/files/3617236/tpcc_asan.txt)

**Comment by mbutrovich** [comment]
I'll try to track down @wangziqi2013.

**Comment by lmwnshn** [comment]
This will be "fixed" by #1224 (aka we ignore it). Closing in favor of newer #791.
