### ISSUE TITLE
Add parallel index insertion during recovery

### ISSUE THREAD

**Issue by GustavoAngulo** [cmu-db/noisepage#560]
Currently, after we have all the indexes we need to update for a given `LogRecord` in the `RecoveryManager`, we insert into each index sequentially. There's no conflicts between index inserts, and each insert is guaranteed to succeed. Thus, we can do these inserts and key creations in parallel using some sort of worker pool. The worker pool wouldn't need to be very large since in the average case theres not more than a handful of indexes on a single table.

**Comment by wgy8283335** [comment]
Hi, I'd like to take this issue. But as I'm a beginner. I do not know which cpp file needs to be modified to implementing the parallel index insertion. Could you give me a suggestion?

**Comment by GustavoAngulo** [comment]
[This `for` loop](https://github.com/cmu-db/terrier/blob/ebc91b06e6ece1131627726bd0401cd190adb5ac/src/storage/recovery/recovery_manager.cpp#L323-L355) is what I intended to parallelize. Note that you will need multiple buffers to construct the index keys, as multiple threads can't use the same buffer.

**Comment by wgy8283335** [comment]
@GustavoAngulo Hi, is the recovery_manager.cpp removed from the master branch?

**Comment by lmwnshn** [comment]
We never did merge the recovery stuff and it sounds like @tpan496 is forging a bit of his own path here. Closing this issue.
