### ISSUE TITLE
Support expressions/partial index in parser/plannodes for CREATE INDEX

### ISSUE THREAD

**Issue by yeshengm** [cmu-db/noisepage#583]
The current parser for `CREATE INDEX` is a bit hacky in #376 . Actually the `class IndexAttr` introduced in this PR makes it impossible for `CreateIndexPlanNode` to peek whether an index attribute is a table column or an abstract expression. I'd suggest unify them in the parser at the first place (using `ColumnValueExpression`).

ping @wenxuanqiu @lmwnshn

**Comment by mbutrovich** [comment]
The PR you linked has a test that seems to demonstrate how you can test an expression's type. COLUMN VALUE is one of the possible enum values returned by asking an AbstractExpression what its type is. Why can't you use that?

**Comment by yeshengm** [comment]
@mbutrovich See the two asserts in `IndexAttr::GetName/GetExpression`. The tests know whether each index attribute is column/expr before hand, therefore they won't hit the issue mentioned above.

**Comment by mbutrovich** [comment]
I'm confused, how does this assert block you?

https://github.com/cmu-db/terrier/blob/master/src/include/parser/create_statement.h#L354

**Comment by yeshengm** [comment]
Because you have to go either way to check whether an index attr is a column name or expression. However, we cannot always be lucky enough to enter the correct code path.

**Comment by lmwnshn** [comment]
I agree something needs to change, how did you picture using `ColumnValueExpression` though? That doesn't seem related to an index attribute.

I'm thinking you will need to introduce basically an enum or a boolean to IndexAttr, which tells you whether it holds a name or an expression.

**Comment by yeshengm** [comment]
I'd prefer `std::variant` or just convert the column name to a single `ColumnValueExpression` with `col_oid` binded.

**Comment by lmwnshn** [comment]
We are explicitly avoiding introducing "brains" into the parser, see [Tianyu](https://github.com/cmu-db/terrier/blob/290f07f7466c897d4d0235fec13f0e78acb20336/src/include/parser/expression/function_expression.h#L94)'s old comments. The column name will not be converted into a column OID, at least in the parser. The earliest that can happen is in the binder.

Where are you using this?

**Comment by yeshengm** [comment]
I'm creating index using `CreateIndexPlanNode`, where you left a TODO to Wen. I think a variant would suffice.

**Comment by lmwnshn** [comment]
std::variant<std::string, common::ManagedPointer<AbstractExpression>> then? Is it convenient for you to do this?

**Comment by yeshengm** [comment]
LGTM. Also there are some minor differences between the actually postgresql syntax and the logical plan (partial index, ASC/DSC, CONCURRENTLY etc). I can fix those later.

**Comment by WLX-happiness** [comment]
hello,i'm rookie

**Comment by lmwnshn** [comment]
I don't remember what this was about but we support CREATE INDEX now.
