### ISSUE TITLE
Add Function Support in Catalog / Binder

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#597]
We need to bring back the ability to store information about functions (both built-ins and UDFs) in the catalog. The binder will then use this new catalog table to map function names to function OIDs (need to merge #475 first). The execution engine will then perform a look-up at runtime to get the function pointer for a given OID.

You can refer to the `ProcCatalogEntry` and `LanguageCatalogEntry` implementations from the old code on what they should store:

https://github.com/cmu-db/peloton/blob/master/src/include/catalog/proc_catalog.h
https://github.com/cmu-db/peloton/blob/master/src/include/catalog/language_catalog.h

Here is a rough outline of the steps to get started on this:

1. Add the `pg_language` and `pg_proc` tables to the catalog (`src/include/catalog/postgres`). Check with @jrolli on how to bootstrap these tables. Initially you will only need to bootstrap `pg_language`.

2. You next need to figure out how the execution engine handles mapping built-in function names to function pointers. Check with @pmenon / @amlatyrngom on how they doing this. I think that it is similar to how we did things in the old Peloton code. If this is true, then you can refer to the Spring 2018 DB course on how to create a new SQL function: https://15721.courses.cs.cmu.edu/spring2018/project1.html

3. Once we know what built-in functions the current execution engine supports, go back to the catalog bootstrap code and add entries for those functions.

4. We then will restore the `BindNodeVisitor::Visit` method for handling `parser::FunctionExpression` (again, after we merge #475). This code is currently commented out. It will match the function name + input arguments (not sure about return type?) with a corresponding catalog entry.

**Comment by GustavoAngulo** [comment]
I will also add that with how the catalog is designed, and depending how you implement the catalog functions, this will require adding some additional logic to the recovery manager in order to make these tables recoverable.

**Comment by lmwnshn** [comment]
We have functions!
