### ISSUE TITLE
Investigate slow compilation

### ISSUE THREAD

**Issue by pmenon** [cmu-db/noisepage#623]
I've noticed Terrier takes unusually long to compile.

For ~49kLOC, it takes 3m41s to compile+link with 8 threads. This is ~222 line/second.

I have a standalone TPL codebase that's ~27kLOC that takes 38s to compile with 8 threads. This is ~952 line/second, more than 4x faster.

This issue is to investigate and track why compilation is slow.

EDIT: This is just to compile the `tpl` target. The full compilation with unittests and benchmarks takes far longer.

**Comment by lmwnshn** [comment]
@weihang7 offered to look at it. He spent a long time looking at speeding up linking (gold and friends).

**Comment by apavlo** [comment]
The proposal is to try compiling out spdlog and see whether that makes a difference.

**Comment by lmwnshn** [comment]
Here are the compilation times on my machine (make -j1 &> banana.txt)

[banana.txt](https://github.com/cmu-db/terrier/files/3838430/banana.txt)

**Comment by mbutrovich** [comment]
I have a branch that does some tricks with the indexes that brings the build time down on dev4 from ~4m30 to ~3m. Seeing if that extends to other machines before opening a PR.

**Comment by pmenon** [comment]
We should be consistent with both thread counts and the target we're building. My numbers build just the shared library and `tpl` binary - no unittests or benchmarks.

I quickly checked `spdlog` and it accounts for ~ 6% 3m28s to 3m8s.

**Comment by mbutrovich** [comment]
It looks like newer releases of spdlog support compilation as a standalone library for static linking, along with CMake support. No idea how much was modified (if at all) when it was first brought into the codebase. Might just be a matter of updating stuff in third_party and fiddling with CMake.

**Comment by mbutrovich** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-9.0-Time-Trace

This is what I used to trace stuff.

**Comment by lmwnshn** [comment]
Papered over with unity builds in #1224.
