### ISSUE TITLE
Log Test assumes 16 bytes attributes are varlen

### ISSUE THREAD

**Issue by tli2** [cmu-db/noisepage#637]
Which sounds like a problematic assumption long-term.

https://github.com/cmu-db/terrier/blob/643fdf49212d8ab0f9f3eaefb9a53006ef5a9b13/test/storage/log_test.cpp#L141

**Comment by lmwnshn** [comment]
Looks fixed to me, `if (attr_sizes[i] == AttrSizeBytes(VARLEN_COLUMN)) {`.
