### ISSUE TITLE
Selectivity Calculations with regards to ParameterOffsets

### ISSUE THREAD

**Issue by 17zhangw** [cmu-db/noisepage#657]
As Lin mentioned in the comments on PR#600, the `StatsCalculator` uses the `ParameterOffset` value directly which makes the selectivity meaningless. 

Some high level discussion is needed to develop the necessary heuristics for calculating selectivities when dealing with `ParameterOffsets`. This issue is aimed at tracking/keeping a reminder of this issue within the Optimizer's Stats component.

**Comment by jkosh44** [comment]
Fixed in this commit specifically for those that are interested: https://github.com/cmu-db/noisepage/pull/1504/commits/44c9d79e2b500eb7b3fa89a5a898469581d6c8fd
