### ISSUE TITLE
Switch to Dynamic Linking

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#813]
We are using static linking for all of the tests + benchmarks. That makes the linking super long. IIRC, there was a problem with using ASAN on OSX with dynamic linked binaries, but I don't think it is an issue any more.

I think it's just a matter of making a switch in our cmake files to enable dynamic linking.

**Comment by lmwnshn** [comment]
Will be addressed by #1224 in two ways: lld for faster linking, and actual proper dynamic linking made possible by splitting up dependencies.

It was a _little_ more than just making a switch.
