### ISSUE TITLE
Convert Java JDBC Tests to JUnit

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#818]
There is old Java-based testing code in `script/testing/jdbc/` that is currently not being executed. This code is random. They don't have programmatic checks for correctness. Many of them just print to stdout.

We should port over the following files into `script/testing/junit/` and switch them to use Junit's API:

* `PelotonTypeTest.java` (rename to `TypeTest`)
* `PelotonErrorTest.java` (rename to `ErrorTest`)
* `PelotonBasicTest.java` (these should broken up and divided into existing files based on query types).

All other files can be removed (`SSLTest.java` and `StocklevelTest.java`). The entire directory can also be removed as well.

As part of converting the files, we should remove **all** calls to `System.err` and `System.out` so that people don't get the wrong idea about how to write tests.

**Comment by lmwnshn** [comment]
It was converted.
