### ISSUE TITLE
Python Test Harness: Use Unique Port Numbers

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#867]
I hit an error after merging in the new testing harness this morning that I had not seen before:

http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/504/pipeline/117

We were not able to start the DBMS because another process was listening on the same socket. This is unexpected, because I thought that running in a container would isolate our process from others (@crd477 is this true?). 

You can see from the debug log that we attempt to connect to the process that we started (PID=29226) but fail. We then connect to another instance of the DBMS (PID=29250). I'm not sure if that was the second one that we started or from another container?

We should probably select a random port # to start the DBMS to avoid these collisions. We still need to make sure that the DBMS we connect to is the one that we started.

**Comment by crd477** [comment]
> I hit an error after merging in the new testing harness this morning that I had not seen before:
> 

I have not seen this one before either.

> We were not able to start the DBMS because another process was listening on the same socket. This is unexpected, because I thought that running in a container would isolate our process from others (@crd477 is this true?).
> 

Yes, that is true.  Docker containers run in separate `network_namespaces(7)` such that 15271/tcp in one container is distinct from 15271/tcp in another container.  Could it be that a running process was still leftover from the previous unittest or check-tpl stage?

> You can see from the debug log that we attempt to connect to the process that we started (PID=29226) but fail. We then connect to another instance of the DBMS (PID=29250). I'm not sure if that was the second one that we started or from another container?
> 
> We should probably select a random port # to start the DBMS to avoid these collisions. We still need to make sure that the DBMS we connect to is the one that we started.

This might be more aggravation than it's worth if this particular failure was a one-off fluke (and I think it might be).

**Comment by bialesdaniel** [comment]
Has this occurred again? or should I mark it as won't fix for now, until this occurs again?

**Comment by lmwnshn** [comment]
We instead have a shoot em dead script, #1190.
