### ISSUE TITLE
SQLSmith failure connecting to terrier

### ISSUE THREAD

**Issue by jazzplato** [cmu-db/noisepage#982]
I am trying to use [SQLSmith](https://github.com/anse1/sqlsmith) to conduct fuzzing tests for the terrier. However, the following error occurred upon the connection.
```
# sqlsmith --target="host=localhost port=15721 dbname=terrier"
SQLsmith v1.2.1
ERROR:  Procedure not registered
```

Meanwhile, I tried using SQLSmith for Postgres, which worked normally. I have ported out the [SQLSmith query log](http://incrudibles-testing.db.pdl.cmu.edu/sqlsmith/logs/sqlsmith_queries.log) and [Postgres CSV log with the accepted queries](http://incrudibles-testing.db.pdl.cmu.edu/sqlsmith/logs/postgresql-2020-06-23_164040.csv) for troubleshooting purpose.

**Comment by jazzplato** [comment]
BTW, the logs I dumped are the first 100 queries.

**Comment by mbutrovich** [comment]
Same error we've seen in some other tools trying to speak Postgres: `select version()` fails.

![Screen Shot 2020-06-23 at 1 34 29 PM](https://user-images.githubusercontent.com/6855576/85435981-494fc180-b556-11ea-8880-ba1ee4846e65.png)

**Comment by lmwnshn** [comment]
version() was added, closing.
